### ISSUE TITLE
Bonuses jsons do not have questions or answers

### ISSUE THREAD

**Issue by AnuragGowda** [UlyssesInvictus/QuizDB#14]
A bonus json contains the following:

{
id: 41561,
number: 12,
round: "04_fichte09",
category_id: 25,
subcategory_id: 66,
quinterest_id: null,
tournament_id: 144,
leadin: "Answer the following about these very “human” works of philosophy. For 10 points each –",
created_at: "2019-10-15T23:47:46.076Z",
updated_at: "2019-10-15T23:47:46.076Z",
errors_count: 0,
formatted_leadin: "Answer the following about these very “human” works of philosophy. For 10 points each –"
}

but there is no actual question or answer?

**Comment by UlyssesInvictus** [comment]
That's just that particular bonus. QuizDB still contains numerous questions that were imported from Quinterest and lacked question data.

Closing, as this isn't a technical issue (or, is, but not one addressable by a pull request). You may wish to report this in the internal admin interface instead (quizdb.org/admin).

**Comment by AKushWarrior** [comment]
@UlyssesInvictus consider reopening? I checked pretty much all the high school packets from the past few years and each of them had this issue for every bonus. I can see the questions and answers from the admin interface, but when exported to JSON/CSV/XML, they aren't present.
